/*
 * THIS FILE IS A PART OF THE ETSSOS PROJECT AND IS LICENSED UNDER THE MIT LICENSE
 * 
 * SEE (LICENSE)[/LICENSE] FOR MORE INFORMATION
 *
 *
 * NAME       : drivers/gpio/gpio.h
 * DESCRIPTION: Basic DRIVERS_GPIO driver for 8266
 */

#ifndef _ETSSOS_DRIVERS_GPIO_H_
#define _ETSSOS_DRIVERS_GPIO_H_

#include "../common.h"
#include "../iomux.h"

#define DRIVERS_GPIO_PERI    0x60000300
#define DRIVERS_GPIO_PIN_CNT 16

#define DRIVERS_GPIO_OUT             (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000000))
#define DRIVERS_GPIO_OUT_W1TS        (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000004))
#define DRIVERS_GPIO_OUT_W1TC        (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000008))
#define DRIVERS_GPIO_ENA             (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x0000000C))
#define DRIVERS_GPIO_ENA_W1TS        (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000010))
#define DRIVERS_GPIO_ENA_W1TC        (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000014))
#define DRIVERS_GPIO_IN              (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000018))
#define DRIVERS_GPIO_STATUS          (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x0000001C))
#define DRIVERS_GPIO_STATUS_W1TS     (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000020))
#define DRIVERS_GPIO_STATUS_W1TC     (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000024))
#define Drivers_GPIO_PIN(__pinnum__) (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + ((0x0000000a + (__pinnum__)) * 4)))
#define DRIVERS_GPIO_SIGMA_DELTA     (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000068))
#define DRIVERS_GPIO_RTC_CALIB_SYNC  (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x0000006C))
#define DRIVERS_GPIO_RTC_CALIB_VALUE (*(volatile uint32_t*)(DRIVERS_GPIO_PERI + 0x00000070))

typedef enum word_sized DRIVERS_GPIO_OUT_BIT {
    DRIVERS_GPIO_OUT_BT_SEL = 0xFFFF0000,
    DRIVERS_GPIO_OUT_DATA   = 0x0000FFFF,
} DRIVERS_GPIO_OUT_BIT;

typedef enum word_sized DRIVERS_GPIO_OUT_W1TS_BIT {
    DRIVERS_GPIO_OUT_W1TS_W1TS = 0xFFFF0000,
    DRIVERS_GPIO_OUT_W1TS_DATA = 0x0000FFFF,
} DRIVERS_GPIO_OUT_W1TS_BIT;

typedef enum word_sized DRIVERS_GPIO_OUT_W1TC_BIT {
    DRIVERS_GPIO_OUT_W1TC_W1TS = 0xFFFF0000,
    DRIVERS_GPIO_OUT_W1TC_DATA = 0x0000FFFF,
} DRIVERS_GPIO_OUT_W1TC_BIT;

typedef enum word_sized DRIVERS_GPIO_ENA_BIT {
    DRIVERS_GPIO_ENA_ENA  = 0xFFC00000,
    DRIVERS_GPIO_ENA_SEL  = 0x003F0000,
    DRIVERS_GPIO_ENA_DATA = 0x0000FFFF,
} DRIVERS_GPIO_ENA_BIT;

typedef enum word_sized DRIVERS_GPIO_ENA_W1TS_BIT {
    DRIVERS_GPIO_ENA_W1TS_W1TS = 0xFFFF0000,
    DRIVERS_GPIO_ENA_W1TS_DATA = 0x0000FFFF,
} DRIVERS_GPIO_ENA_W1TS_BIT;

typedef enum word_sized DRIVERS_GPIO_ENA_W1TC_BIT {
    DRIVERS_GPIO_ENA_W1TC_W1TC = 0xFFFF0000,
    DRIVERS_GPIO_ENA_W1TC_DATA = 0x0000FFFF,
} DRIVERS_GPIO_ENA_W1TC_BIT;

typedef enum word_sized DRIVERS_GPIO_IN_BIT {
    DRIVERS_GPIO_IN_STRAPPING = 0xFFFF0000,
    DRIVERS_GPIO_IN_DATA      = 0x0000FFFF,
} DRIVERS_GPIO_IN_BIT;

typedef enum word_sized DRIVERS_GPIO_STATUS_BIT {
    DRIVERS_GPIO_STATUS_STATUS = 0xFFFF0000,
    DRIVERS_GPIO_STATUS_INT    = 0x0000FFFF,
} DRIVERS_GPIO_STATUS_BIT;

typedef enum word_sized DRIVERS_GPIO_STATUS_W1TS_BIT {
    DRIVERS_GPIO_STATUS_W1TS_W1TS = 0xFFFF0000,
    DRIVERS_GPIO_STATUS_W1TS_INT  = 0x0000FFFF,
} DRIVERS_GPIO_STATUS_W1TS_BIT;

typedef enum word_sized DRIVERS_GPIO_STATUS_W1TC_BIT {
    DRIVERS_GPIO_STATUS_W1TC_W1TC = 0xFFFF0000,
    DRIVERS_GPIO_STATUS_W1TC_INT  = 0x0000FFFF,
} DRIVERS_GPIO_STATUS_W1TC_BIT;

typedef enum word_sized DRIVERS_GPIO_PIN_BIT {
    DRIVERS_GPIO_PIN_PIN     = 0xFFFFF800,
    DRIVERS_GPIO_PIN_WKU_ENA = 0x00000400,
    DRIVERS_GPIO_PIN_INT_TYP = 0x00000380,
    DRIVERS_GPIO_PIN_DRIVER  = 0x00000004,
    DRIVERS_GPIO_PIN_DATA    = 0x00000001,
} DRIVERS_GPIO_PIN_BIT;

typedef enum word_sized DRIVERS_GPIO_SIGMA_DELTA_BIT {
    DRIVERS_GPIO_SIGMA_DELTA_ENA    = 0x00010000,
    DRIVERS_GPIO_SIGMA_DELTA_PSC    = 0x0000FF00,
    DRIVERS_GPIO_SIGMA_DELTA_TARGET = 0x000000FF,
} DRIVERS_GPIO_SIGMA_DELTA_BIT;

typedef enum word_sized DRIVERS_GPIO_RTC_CALIB_SYNC_BIT {
    DRIVERS_GPIO_RTC_CALIB_SYNC_ENA    = 0x80000000,
    DRIVERS_GPIO_RTC_CALIB_SYNC_PERIOD = 0x000003FF,
} DRIVERS_GPIO_RTC_CALIB_SYNC_BIT;

typedef enum word_sized DRIVERS_GPIO_RTC_CALIB_VALUE_BIT {
    DRIVERS_GPIO_RTC_CALIB_VALUE_RDY      = 0x80000000,
    DRIVERS_GPIO_RTC_CALIB_VALUE_RDY_REAL = 0x40000000,
    DRIVERS_GPIO_RTC_CALIB_VALUE_VALUE    = 0x000FFFFF,
} DRIVERS_GPIO_RTC_CALIB_VALUE_BIT;

typedef enum backing(uint8_t) DRIVERS_GPIO_MODE {
    DRIVERS_GPIO_MODE_INPUT,
    DRIVERS_GPIO_MODE_OUTPUT,
} DRIVERS_GPIO_MODE;

#define Drivers_GPIO_Read(__pinnum__) ((GPIO_IN >> (__pinnum__)) & 1)
#define Drivers_GPIO_Enable(__pinnum__, __ena__) Drivers_IOMUX_SetFunc((__pinnum__), Drivers_IOMUX_GPIO_FuncVector[(__pinnum__)], (__ena__))

void     Drivers_GPIO_Init(void);
void     Drivers_GPIO_SetMode(uint8_t const, DRIVERS_GPIO_MODE const);
void     Drivers_GPIO_Write(uint8_t const, uint16_t const);

#endif /* _ETSSOS_DRIVERS_GPIO_H_ */
