/*
 * THIS FILE IS A PART OF THE ETSSOS PROJECT
 * AND IS LICENSED UNDER THE MIT LICENSE
 * 
 * SEE (LICENSE)[/LICENSE] FOR MORE INFORMATION
 *
 *
 * NAME       : gpio/gpio.h
 * DESCRIPTION: Basic GPIO driver for 8266
 */

#define CPU_CLK_FREQ 26000000
#define TIMER_CLK_FREQ (CPU_CLK_FREQ>>8)

#define IOMUX_PERI 0x60000800
#define GPIO_PERI  0x60000300
