/*
 * THIS FILE IS A PART OF THE ETSSOS PROJECT AND IS LICENSED UNDER THE MIT LICENSE
 * 
 * SEE (LICENSE)[/LICENSE] FOR MORE INFORMATION
 *
 *
 * NAME       : drivers/timer/timer.h
 * DESCRIPTION: Basic UART driver for 8266
 */

#ifndef _ETSSOS_DRIVERS_TIMER_H_
#define _ETSSOS_DRIVERS_TIMER_H_

#include "../common.h"
#include "../../arch/archdef.h"

#define DRIVERS_TIMER_PERI 0x60000600

#define DRIVERS_TIMER_FRC1_LOAD       (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000000))
#define DRIVERS_TIMER_FRC1_CNT        (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000004))
#define DRIVERS_TIMER_FRC1_CTRL_ADDR  (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000008))
#define DRIVERS_TIMER_FRC1_INT_ADDR   (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x0000000C))
#define DRIVERS_TIMER_FRC2_LOAD       (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000020))
#define DRIVERS_TIMER_FRC2_CNT        (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000024))
#define DRIVERS_TIMER_FRC2_CTRL_ADDR  (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000028))
#define DRIVERS_TIMER_FRC2_INT_ADDR   (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x0000002C))
#define DRIVERS_TIMER_FRC2_ALARM_ADDR (*(volatile uint32_t*)(DRIVERS_TIMER_PERI + 0x00000030))

typedef enum word_sized DRIVERS_TIMER_FRC1_LOAD_BIT {
    DRIVERS_TIMER_FRC1_LOAD_ADDR = 0x007FFFFF,
} DRIVERS_TIMER_FRC1_LOAD_BIT;

typedef enum word_sized DRIVERS_TIMER_FRC1_CNT_BIT {
    DRIVERS_TIMER_FRC1_CNT_CNT = 0x007FFFFF,
} DRIVERS_TIMER_FRC1_CNT_BIT;

typedef enum word_sized DRIVERS_TIMER_FRC1_CTRL_ADDR_BIT {
    DRIVERS_TIMER_FRC1_CTRL_ADDR_ADDR    = 0xFFFFFE00,
    DRIVERS_TIMER_FRC1_CTRL_ADDR_INT     = 0x00000100,
    DRIVERS_TIMER_FRC1_CTRL_ADDR_ENA     = 0x00000080,
    DRIVERS_TIMER_FRC1_CTRL_ADDR_RLD     = 0x00000040,
    DRIVERS_TIMER_FRC1_CTRL_ADDR_PSC_DIV = 0x0000000C,
    DRIVERS_TIMER_FRC1_CTRL_ADDR_INT_TYP = 0x00000001,
} DRIVERS_TIMER_FRC1_CTRL_ADDR_BIT;

typedef enum word_sized DRIVERS_TIMER_FRC1_INT_ADDR_BIT {
    DRIVERS_TIMER_FRC1_INT_ADDR_ADDR = 0xFFFFFFFE,
    DRIVERS_TIMER_FRC1_INT_ADDR_CLR  = 0x00000001,
} DRIVERS_TIMER_FRC1_INT_ADDR_BIT;

typedef enum word_sized DRIVERS_TIMER_FRC2_CTRL_ADDR_BIT {
    DRIVERS_TIMER_FRC2_CTRL_ADDR_ADDR    = 0xFFFFFE00,
    DRIVERS_TIMER_FRC2_CTRL_ADDR_INT     = 0x00000100,
    DRIVERS_TIMER_FRC2_CTRL_ADDR_ENA     = 0x00000080,
    DRIVERS_TIMER_FRC2_CTRL_ADDR_RLD     = 0x00000040,
    DRIVERS_TIMER_FRC2_CTRL_ADDR_PSC_DIV = 0x0000000C,
    DRIVERS_TIMER_FRC2_CTRL_ADDR_INT_TYP = 0x00000001,
} DRIVERS_TIMER_FRC2_CTRL_ADDR_BIT;

typedef enum word_sized DRIVERS_TIMER_FRC2_INT_ADDR_BIT {
    DRIVERS_TIMER_FRC2_INT_ADDR_ADDR = 0xFFFFFFFE,
    DRIVERS_TIMER_FRC2_INT_ADDR_CLR  = 0x00000001,
} DRIVERS_TIMER_FRC2_INT_ADDR_BIT;

#define DRIVERS_TIMER_PRESCALE_DIVIDER  1
#define DRIVERS_TIMER_MS_TO_TICK_SCALAR (CPU_CLK_FREQ / DRIVERS_TIMER_PRESCALE_DIVIDER)

#define DRIVERS_TIMER_FRC1_INTERVAL_TICKS ((uint32_t)DRIVERS_TIMER_MS_TO_TICK_SCALAR * 1000)
#define DRIVERS_TIMER_FRC2_INTERVAL_TICKS ((uint32_t)DRIVERS_TIMER_MS_TO_TICK_SCALAR * 1000)

extern volatile uint32_t DRIVERS_UART0_CLK_FREQ; /* Initial state is undefined, call UART_Init before use. */

void Drivers_Timer_Init(void);
void Drivers_Timer_FRC1_Interrupt_Handler(void);
void Drivers_Timer_FRC2_Interrupt_Handler(void);

#endif /* _ETSSOS_DRIVERS_TIMER_H_ */
