/*
 * THIS FILE IS A PART OF THE ETSSOS PROJECT
 * AND IS LICENSED UNDER THE MIT LICENSE
 * 
 * SEE (LICENSE)[/LICENSE] FOR MORE INFORMATION
 *
 *
 * NAME       : kernel/interrupt.h
 * DESCRIPTION: Interrupt handling utilities
 */

#ifndef _ETSSOS_KERNEL_INTERRUPT_H_
#define _ETSSOS_KERNEL_INTERRUPT_H_

#include "../drivers/common.h"

typedef enum backing(uint8_t) KERNEL_INTERRUPT_TYPE {
    KERNEL_INTERRUPT_ILLEGALINSTRUCTION,
    KERNEL_INTERRUPT_SYSCALL,
    KERNEL_INTERRUPT_INSTRUCTIONFETCHERROR,
    KERNEL_INTERRUPT_LOADSTOREERROR,
    KERNEL_INTERRUPT_LEVEL1INTERRUPT,
    KERNEL_INTERRUPT_ALLOCA,
    KERNEL_INTERRUPT_DIVIDEBYZERO,
    RESERVED_1,
    KERNEL_INTERRUPT_PRIVILEGEMISMATCH,
    KERNEL_INTERRUPT_LOADSTOREALIGNMENT,
    RESERVED_2,
    RESERVED_3,
    KERNEL_INTERRUPT_INSTRPIFDATAERROR,
    KERNEL_INTERRUPT_LOADSTOREPIFDATAERROR,
    KERNEL_INTERRUPT_INSTRPIFADDRERROR,
    KERNEL_INTERRUPT_LOADSTOREPIFADDRERROR,
    KERNEL_INTERRUPT_INSTTLBMISS,
    KERNEL_INTERRUPT_INSTTLBMULTIHIT,
    KERNEL_INTERRUPT_INSTFETCHPRIVILEGEMISMATCH,
    RESERVED_4,
    KERNEL_INTERRUPT_INSTFETCHPROHIBITED,
    RESERVED_5,
    RESERVED_6,
    RESERVED_7,
    KERNEL_INTERRUPT_LOADSTORETLBMISS,
    KERNEL_INTERRUPT_LOADSTORETLBMULTIHIT,
    KERNEL_INTERRUPT_LOADSTOREPRIVILEGEMISMATCH,
    RESERVED_9,
    KERNEL_INTERRUPT_LOADPROHIBITED,
    KERNEL_INTERRUPT_STOREPROHIBITED,
    RESERVED_A,
    RESERVED_B,
    KERNEL_INTERRUPT_COPROCESSOR0DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR1DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR2DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR3DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR4DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR5DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR6DISABLED,
    KERNEL_INTERRUPT_COPROCESSOR7DISABLED,
} KERNEL_INTERRUPT_TYPE;

typedef enum backing(uint8_t) KERNEL_INTERRUPT_SOURCE {
    KERNEL_INTERRUPT_WDEV_FIQ    = 0,
    KERNEL_INTERRUPT_SLC         = 1,
    KERNEL_INTERRUPT_SPI         = 2,
    KERNEL_INTERRUPT_RTC         = 3,
    KERNEL_INTERRUPT_GPIO        = 4,
    KERNEL_INTERRUPT_UART        = 5,
    KERNEL_INTERRUPT_TICK        = 6,
    KERNEL_INTERRUPT_SOFT        = 7,
    KERNEL_INTERRUPT_WDT         = 8,
    KERNEL_INTERRUPT_TIMER_FRC1  = 9,
    KERNEL_INTERRUPT_TIMER_FRC2  = 10,
    KERNEL_INTERRUPT_COUNT       = 11,
} KERNEL_INTERRUPT_SOURCE;

typedef void (*Kernel_Interrupt_Handler)(void);

void Kernel_Interrupt_Register(KERNEL_INTERRUPT_SOURCE const, Kernel_Interrupt_Handler const);
void Kernel_Interrupt_Dispatch(void);

#endif /* _ETSSOS_KERNEL_INTERRUPT_H_ */
